import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { initializeStoryblok } from '@/lib/storyblok'

// Initialize Storyblok for server-side rendering
initializeStoryblok()

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Storyblok Next App',
  description: 'Generated by Storyblok blueprints',
  icons: {
    icon: [{ url: '/favicon.svg', type: 'image/svg+xml' }],
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  )
}
